interface ProductStrings {
  MANAGE_PRODUCTS_TITLE: string;
  PRODUCT_TABLE_COLUMN_ITEM_NUMBER: string;
  PRODUCT_TABLE_COLUMN_NAME: string;
  PRODUCT_TABLE_COLUMN_UNIT_MEASUREMENT: string;
  PRODUCT_TABLE_COLUMN_UPC: string;
  PRODUCT_TABLE_COLUMN_BRAND: string;
  PRODUCT_TABLE_TITLE: string;
  PRODUCT_BRAND_SELECTION: string;
  PRODUCT_VENDOR_SELECTION: string;
}

const PRODUCT_STRINGS: ProductStrings = {
  MANAGE_PRODUCTS_TITLE: 'Manage Products',
  PRODUCT_TABLE_COLUMN_ITEM_NUMBER: 'Item Number',
  PRODUCT_TABLE_COLUMN_NAME: 'Name',
  PRODUCT_TABLE_COLUMN_UNIT_MEASUREMENT: 'UM',
  PRODUCT_TABLE_COLUMN_UPC: 'UPC',
  PRODUCT_TABLE_COLUMN_BRAND: 'Brand',
  PRODUCT_TABLE_TITLE: 'Products',
  PRODUCT_BRAND_SELECTION: 'Select Brand',
  PRODUCT_VENDOR_SELECTION: 'Select Vendor',
};

export default PRODUCT_STRINGS;
