interface ProductStrings {
  MANAGE_PROCUCTS_TITLE: string;
  PROCUCT_TABLE_COLUMN_ITEM_NUMBER: string;
  PROCUCT_TABLE_COLUMN_NAME: string;
  PROCUCT_TABLE_COLUMN_UNIT_MEASUREMENT: string;
  PROCUCT_TABLE_COLUMN_UPC: string;
  PROCUCT_TABLE_TITLE: string;
}

const PRODUCT_STRINGS: ProductStrings = {
  MANAGE_PROCUCTS_TITLE: 'Manage Products',
  PROCUCT_TABLE_COLUMN_ITEM_NUMBER: 'Item Number',
  PROCUCT_TABLE_COLUMN_NAME: 'Name',
  PROCUCT_TABLE_COLUMN_UNIT_MEASUREMENT: 'UM',
  PROCUCT_TABLE_COLUMN_UPC: 'UPC',
  PROCUCT_TABLE_TITLE: 'Products',
};

export default PRODUCT_STRINGS;
