interface ProductStrings {
  MANAGE_PRODUCTS_TITLE: string;
  EDIT_PRODUCTS_DETAILS_TITLE: string;
  PRODUCT_FORM_INFOR_TITLE: string;
  PRODUCT_FORM_PLATFORM_TITLE: string;
  PRODUCT_FORM_BRAND: string;
  PRODUCT_FORM_DETAILS: string;
  PRODUCT_FORM_GUARANTEED_ANALYSIS: string;
  PRODUCT_FORM_INGREDIENTS: string;
  PRODUCT_FORM_LONG_DESCRIPTION: string;
  PRODUCT_FORM_DESCRIPTION: string;
  PRODUCT_FORM_EDLP: string;
  PRODUCT_FORM_IMAGE_NAME: string;
  PRODUCT_FORM_ITEM_NUMBER: string;
  PRODUCT_FORM_FLAVOR: string;
  PRODUCT_FORM_HIGHLIGHTS: string;
  PRODUCT_FORM_SIZE: string;
  PRODUCT_FORM_UM: string;
  PRODUCT_TABLE_COLUMN_ITEM_NUMBER: string;
  PRODUCT_TABLE_COLUMN_NAME: string;
  PRODUCT_TABLE_COLUMN_UNIT_MEASUREMENT: string;
  PRODUCT_TABLE_COLUMN_UPC: string;
  PRODUCT_TABLE_COLUMN_BRAND: string;
  PRODUCT_TABLE_TITLE: string;
  PRODUCT_BRAND_SELECTION: string;
  PRODUCT_VENDOR_SELECTION: string;
}

const PRODUCT_STRINGS: ProductStrings = {
  MANAGE_PRODUCTS_TITLE: 'Manage Products',
  EDIT_PRODUCTS_DETAILS_TITLE: 'Edit Product',
  PRODUCT_FORM_INFOR_TITLE: 'Infor',
  PRODUCT_FORM_PLATFORM_TITLE: 'Platform',
  PRODUCT_FORM_BRAND: 'Brand',
  PRODUCT_FORM_DETAILS: 'Product Details',
  PRODUCT_FORM_GUARANTEED_ANALYSIS: 'Guaranteed Analysis',
  PRODUCT_FORM_INGREDIENTS: 'Ingredients',
  PRODUCT_FORM_LONG_DESCRIPTION: 'Long Description',
  PRODUCT_FORM_DESCRIPTION: 'Description',
  PRODUCT_FORM_EDLP: 'EDLP',
  PRODUCT_FORM_IMAGE_NAME: 'Image Name',
  PRODUCT_FORM_ITEM_NUMBER: 'Item Number',
  PRODUCT_FORM_FLAVOR: 'Flavor',
  PRODUCT_FORM_HIGHLIGHTS: 'Highlights',
  PRODUCT_FORM_SIZE: 'Size',
  PRODUCT_FORM_UM: 'UM',
  PRODUCT_TABLE_COLUMN_ITEM_NUMBER: 'Item Number',
  PRODUCT_TABLE_COLUMN_NAME: 'Name',
  PRODUCT_TABLE_COLUMN_UNIT_MEASUREMENT: 'UM',
  PRODUCT_TABLE_COLUMN_UPC: 'UPC',
  PRODUCT_TABLE_COLUMN_BRAND: 'Brand',
  PRODUCT_TABLE_TITLE: 'Products',
  PRODUCT_BRAND_SELECTION: 'Select Brand',
  PRODUCT_VENDOR_SELECTION: 'Select Vendor',
};

export default PRODUCT_STRINGS;
